version: '3.1'
services:
    web:
        image: nginx:latest
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./app:/app
            - ./site.conf:/etc/nginx/conf.d/site.conf
            - ./logs:/var/log/nginx/
        links:
            - php
    
    php:
        build: '.'
        restart: always
        volumes:
            - ./app:/app
        env_file:
            - .env
        links:
            - db

    db:
        image: mariadb
        restart: always
        env_file:
            - .env
        volumes:
            - ./data:/var/lib/mysql
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080            